pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = '1.21.10'
include 'Reliquary'
include 'SophisticatedCore'
include 'SophisticatedBackpacks'
include 'SophisticatedBackpacksCreateIntegration'
include 'SophisticatedStorage'
include 'SophisticatedStorageCreateIntegration'
include 'SophisticatedStorageInMotion'
include 'SophisticatedItemActions'

include 'workspace'
