org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.52-beta
neo_version_range=[26.3.0.47-beta,26.4.0)
loader_version_range=[4,)

mod_id=devclientautomation
mod_name=Dev Client Automation
mod_license=All Rights Reserved
mod_version=1.0.7
mod_group_id=net.p3pp3rf1y
mod_authors=P3pp3rF1y
mod_description=Dev-only client automation bridge for local Minecraft testing.

emi_version=1.1.22+1.21.1
jei_mc_version=26.3-neoforge
jei_version=31.7.0.45
rei_version=26.3.823
cloth_config_version=26.3.159
architectury_version=22.0.3
