@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.p3pp3rf1y.devclientautomation.scenarios.core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
