plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.134'
    id "net.darkhax.curseforgegradle" version "1.1.15"
    id "com.modrinth.minotaur" version "2.+"
    id "com.diffplug.spotless" version "7.0.4"
    id "org.openrewrite.rewrite" version "7.35.0"
}

def sharedCodeQualityScript = file('../gradle/code-quality.gradle')
apply from: sharedCodeQualityScript.exists() ? sharedCodeQualityScript : 'https://raw.githubusercontent.com/P3pp3rF1y/MultiWorkspace/1.21.11/gradle/code-quality.gradle'

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

spotless {
    enforceCheck = false
    def spotlessFiles = findProperty("spotlessFiles")

    java {
        target spotlessFiles == null ? "src/*/java/**/*.java" : spotlessFiles.toString().split(/\s*,\s*/).findAll { it.endsWith(".java") }

        eclipse().configFile "$projectDir/codeformat/eclipse-java-format.xml"
        importOrder "", "javax", "java", "\\#"
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }

    groovyGradle {
        target spotlessFiles == null ? "*.gradle" : spotlessFiles.toString().split(/\s*,\s*/).findAll { it.endsWith(".gradle") }
        trimTrailingWhitespace()
        endWithNewline()
    }
}

repositories {
    maven {
        url = "https://mvn.devos.one/snapshots"
        content {
            includeGroupByRegex "com.tterrag.*"
        }
    }
    // maven { url 'https://www.dogforce-games.com/maven/' }
    maven { // JEI
        url "https://dvs1.progwml6.com/files/maven"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven { // Patchouli
        url "https://maven.blamejared.com"
        content {
            includeGroup "mezz.jei"
            includeGroup "vazkii.patchouli"
        }
    }
    // maven { // TOP
    //     url "https://maven.k-4u.nl"
    //     content {
    //         includeGroup "mcjty.theoneprobe"
    //     }
    // }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup 'top.theillusivec4.curios'
        }
    }
    maven {
        url = "https://maven.createmod.net"
        content {
            includeGroupByRegex "com.simibubi.*"
            includeGroupByRegex "net.createmod.*"
            includeGroupByRegex "dev.engine-room.*"
        }
    }
    maven {
        url = "https://maven.twelveiterations.com/repository/maven-public/"
        content {
            includeGroup "net.blay09.mods"
        }
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
            // IMPORTANT: do NOT use gradleMetadata()
        }
    }
    maven {
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup "dev.architectury"
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
        content {
            includeGroup "dev.emi"
        }
    }
}

version = '1.0'
group = 'com.yourname.modid' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
base {
    archivesName = 'modid'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

def recipeViewer = (findProperty("recipe_viewer") ?: "jei").toString()
def minimalDevClientRuntime = (findProperty("dev_client_minimal_runtime") ?: "false").toString().toBoolean()

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
        }

        client2 {
            client()

            gameDirectory = file('runs/client2')
            programArguments.addAll '--username', 'Dev2'
        }

        server {
            server()
        }

        clientData {
            clientData()
            programArguments.addAll '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', sourceSets.main.resources.srcDirs[0].absolutePath
        }
    }

    mods {
        "sophisticatedcore" {
            sourceSet(project(':SophisticatedCore').sourceSets.main)
        }
        "sophisticatedbackpacks" {
            sourceSet(project(':SophisticatedBackpacks').sourceSets.main)
        }
/*
        "sophisticatedbackpackscreateintegration" {
            sourceSet(project(':SophisticatedBackpacksCreateIntegration').sourceSets.main)
        }
*/
        "sophisticatedstorage" {
            sourceSet(project(':SophisticatedStorage').sourceSets.main)
        }
        "sophisticatedstorageinmotion" {
            sourceSet(project(':SophisticatedStorageInMotion').sourceSets.main)
        }
        "sophisticateditemactions" {
            sourceSet(project(':SophisticatedItemActions').sourceSets.main)
        }
        "sophisticatedinventoryinteractions" {
            sourceSet(project(':SophisticatedInventoryInteractions').sourceSets.main)
        }
/*
        "sophisticatedstoragecreateintegration" {
            sourceSet(project(':SophisticatedStorageCreateIntegration').sourceSets.main)
        }
*/
        "reliquary" {
            sourceSet(project(':Reliquary').sourceSets.main)
        }
        "devclientautomation" {
            sourceSet(project(':DevClientAutomation').sourceSets.main)
        }
    }
}

dependencies {

/*
    if (findProject(':TheOneProbe') != null) {
        implementation project(':TheOneProbe')
    } else {
        implementation project.dependencies.create("mcjty.theoneprobe:theoneprobe:${top_version}") {
            transitive = false
        })
    }
*/

//    compileOnly "mezz.jei:jei-${jei_mc_version}-api:${jei_version}")

    if (findProject(':SophisticatedCore') != null) {
        implementation project(':SophisticatedCore')
    }
    if (findProject(':SophisticatedBackpacks') != null) {
        implementation project(':SophisticatedBackpacks')
    }
/*
    if (findProject(':SophisticatedBackpacksCreateIntegration') != null) {
        implementation project(':SophisticatedBackpacksCreateIntegration')
    }
*/
    if (findProject(':SophisticatedStorage') != null) {
        implementation project(':SophisticatedStorage')
    }
    if (findProject(':SophisticatedStorageInMotion') != null) {
        implementation project(':SophisticatedStorageInMotion')
    }
    if (findProject(':SophisticatedItemActions') != null) {
        implementation project(':SophisticatedItemActions')
    }
    if (findProject(':SophisticatedInventoryInteractions') != null) {
        implementation project(':SophisticatedInventoryInteractions')
    }
    if (findProject(':DevClientAutomation') != null) {
        implementation project(':DevClientAutomation')
    }
/*
    if (findProject(':SophisticatedStorageCreateIntegration') != null) {
        implementation project(':SophisticatedStorageCreateIntegration')
    }
*/

    if (!minimalDevClientRuntime) {
        // Drop extra test mods into workspace/local-mods to load them in dev runs.
        runtimeOnly fileTree(dir: 'local-mods', include: ['*.jar'])

        runtimeOnly "curse.maven:jade-324717:${jade_cf_file_id}"
    //runtimeOnly "curse.maven:embeddium-908741:5213210"
/*
    runtimeOnly("com.simibubi.create:create-${create_mc_version}:${create_version}") {
        transitive = false
    }
    runtimeOnly ("net.createmod.ponder:Ponder-NeoForge-${create_mc_version}:${ponder_version}") {
        transitive = false
    }
    runtimeOnly ("dev.engine-room.flywheel:flywheel-neoforge-${create_mc_version}:${flywheel_version}"){
        transitive = false
    }
    runtimeOnly "com.tterrag.registrate:Registrate:${registrate_version}"
*/
/*
    runtimeOnly "curse.maven:itemborders-513769:${item_borders_cf_file_id}"
    runtimeOnly "curse.maven:iceberg-520110:${iceberg_cf_file_id}"
    runtimeOnly "curse.maven:prism-638111:${prism_cf_file_id}"
*/
/*
    runtimeOnly "curse.maven:chipped-456956:${chipped_cf_file_id}"
    runtimeOnly "curse.maven:resourcefullib-570073:${resourcefullib_cf_file_id}"
    runtimeOnly "curse.maven:athena-841890:${athena_cf_file_id}"
*/
        runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
        runtimeOnly "net.blay09.mods:balm-neoforge:${balm_version}"
        runtimeOnly "net.blay09.mods:craftingtweaks-neoforge:${craftingtweaks_version}"
/*
    runtimeOnly "curse.maven:caelus-308989:${caelus_cf_file_id}"
    runtimeOnly "curse.maven:mekanismgenerators-268566:${mekanismgenerators_cf_file_id}"
    runtimeOnly "curse.maven:carryon-274259:${carryon_cf_file_id}"
    runtimeOnly "curse.maven:mekanism-268560:5574951"
    runtimeOnly "curse.maven:buildinggadgets-298187:5615703"
    runtimeOnly "curse.maven:mobgrindingutils-254241:6022733"
    runtimeOnly "curse.maven:titanium-287342:5897690"
    runtimeOnly "curse.maven:functionalstorage-556861:6023174"
    runtimeOnly "curse.maven:productivebees-377897:6029033"
    runtimeOnly "curse.maven:caelus-308989:5694215"
    runtimeOnly "curse.maven:curioselytra-317716:5778461"
    runtimeOnly "curse.maven:moonlightlib-499980:${moonlightlib_cf_file_id}"
    runtimeOnly "curse.maven:sawmill-964817:${sawmill_cf_file_id}"
    runtimeOnly "curse.maven:justdirethings-1002348:6369120"
    runtimeOnly "curse.maven:inventorytweaks-976858:6407807"
    runtimeOnly "curse.maven:inventoryessentials-368825:6179258"
    runtimeOnly "curse.maven:twilightforest-227639:6472889"

    runtimeOnly "curse.maven:guideme-1173950:6396436"
    runtimeOnly "curse.maven:AE2-223794:6399563"
*/

//    runtimeOnly "curse.maven:spark-361579:5971514"

/*
    runtimeOnly "curse.maven:craftingstation-318551:5569165"

    runtimeOnly "curse.maven:mousetweaks-60089:5637846"

*/
        runtimeOnly "net.blay09.mods:trashslot-neoforge:${trashslot_version}"
        //runtimeOnly "curse.maven:accessories-938917:${accessories_cf_file_id}"
        //runtimeOnly "curse.maven:owolib-532610:${owolib_cf_file_id}"
    }
/*
    runtimeOnly "curse.maven:accessorify-1169634:7306023"
    runtimeOnly "curse.maven:fzzyconfig-1005914:7314236"
    runtimeOnly "curse.maven:kotlinlangforge-1244682:7297263"
*/
/*
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "dev.architectury:architectury-neoforge:${architectury_version}"
*/
    switch (recipeViewer) {
        case "emi":
            runtimeOnly "dev.emi:emi-neoforge:${emi_version}"
            break
        case "rei":
            runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
            runtimeOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
            runtimeOnly "dev.architectury:architectury-neoforge:${architectury_version}"
            break
        case "jei":
            runtimeOnly "mezz.jei:jei-${jei_mc_version}:${jei_version}"
            break
        case "none":
            break
        default:
            throw new GradleException("Unknown recipe_viewer '${recipeViewer}'. Expected emi, rei, jei, or none.")
    }

//    runtimeOnly "dev.emi:emi-neoforge:${emi_version}"

    //runtimeOnly "curse.maven:etf-568563:5921308"
    //runtimeOnly "curse.maven:emf-844662:5722727"

    //runtimeOnly "curse.maven:create-328085:4835191"

    //runtimeOnly "curse.maven:cyclopscore-232758:4905983"
    //runtimeOnly "curse.maven:integratedterminals-295910:4925609"
    //runtimeOnly "curse.maven:integratedynamics-236307:4925678"
    //runtimeOnly "curse.maven:commoncapabilities-247007:4620480"
    //runtimeOnly "curse.maven:integratedtunnels-251389:4782861"

/*
    runtimeOnly "curse.maven:refinedstorage-243076:4465872")
    runtimeOnly "curse.maven:placebo-283644:4629583")
    runtimeOnly "curse.maven:fastworkbench-288885:4579504")
    runtimeOnly "curse.maven:spark-361579:4029757")
    runtimeOnly "dev.emi:emi-forge:1.0.19+1.19.2")
*/
}
