plugins {
    id 'idea'
    id "org.sonarqube" version "3.3"
    id "maven-publish"
    id 'net.neoforged.gradle' version '[6.0.18,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

repositories {
    maven { url "https://maven.tterrag.com/" }
    maven {
        url "https://maven.theillusivec4.top/"
        content {
            includeGroup "top.theillusivec4"
        }
    }
    maven { url 'https://www.dogforce-games.com/maven/' }
    maven { // JEI
        url "https://dvs1.progwml6.com/files/maven"
    }
    maven { // Patchouli
        url "https://maven.blamejared.com"
    }
    maven { // TOP
        url "https://maven.k-4u.nl"
    }
    maven {
        url = "https://maven.createmod.net"
        content {
            includeGroup "com.simibubi.create"
            includeGroupByRegex "net.createmod.*"
            includeGroupByRegex "dev.engine-room.*"
        }
    }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://maven.twelveiterations.com/repository/maven-public/"
        content {
            includeGroup "net.blay09.mods"
        }
    }
}

version = '1.0'
group = 'com.yourname.modid' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'modid'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment' , version: "$parchment_version"
//    accessTransformer = file('workspace/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        configureEach {
            workingDirectory project.file("run/${it.name}")
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            args "--mixin", "sophisticatedstorageinmotion.mixins.json"

            mods {
                if (findProject(':SophisticatedCore') != null) {
                    SophisticatedCore {
                        source project(':SophisticatedCore').sourceSets.main
                    }
                }
                if (findProject(':SophisticatedBackpacks') != null) {
                    SophisticatedBackpacks {
                        source project(':SophisticatedBackpacks').sourceSets.main
                    }
                }
                if (findProject(':SophisticatedBackpacksCreateIntegration') != null) {
                    SophisticatedBackpacksCreateIntegration {
                        source project(':SophisticatedBackpacksCreateIntegration').sourceSets.main
                    }
                }
                if (findProject(':SophisticatedStorage') != null) {
                    SophisticatedStorage {
                        source project(':SophisticatedStorage').sourceSets.main
                    }
                }
                if (findProject(':SophisticatedStorageInMotion') != null) {
                    SophisticatedStorageInMotion {
                        source project(':SophisticatedStorageInMotion').sourceSets.main
                    }
                }
                if (findProject(':SophisticatedStorageCreateIntegration') != null) {
                    SophisticatedStorageCreateIntegration {
                        source project(':SophisticatedStorageCreateIntegration').sourceSets.main
                    }
                }
            }
        }
        client {
        }

        client2 {
            args '--username', 'Dev2'
        }

        server {
        }

        data {
        }
    }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

dependencies {
    // Specify the version of Minecraft to use, If this is any group other then 'net.minecraft' it is assumed
    // that the dep is a ForgeGradle 'patcher' dependency. And it's patches will be applied.
    // The userdev artifact is a special name and will get all sorts of transformations applied to it.
    minecraft "net.neoforged:forge:${minecraft_version}-${neo_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.4:processor'

    if (findProject(':SophisticatedCore') != null) {
        implementation project(':SophisticatedCore')
    }
    if (findProject(':SophisticatedBackpacks') != null) {
        implementation project(':SophisticatedBackpacks')
    }
    if (findProject(':SophisticatedBackpacksCreateIntegration') != null) {
        implementation project(':SophisticatedBackpacksCreateIntegration')
    }
    if (findProject(':SophisticatedStorage') != null) {
        implementation project(':SophisticatedStorage')
    }
    if (findProject(':SophisticatedStorageInMotion') != null) {
        implementation project(':SophisticatedStorageInMotion')
    }
    if (findProject(':SophisticatedStorageCreateIntegration') != null) {
        implementation project(':SophisticatedStorageCreateIntegration')
    }

    runtimeOnly fg.deobf("curse.maven:jade-324717:4614153")
    //runtimeOnly fg.deobf("curse.maven:rubidium-574856:4767529")
    //runtimeOnly fg.deobf("curse.maven:itemborders-513769:${item_borders_cf_file_id}")
    runtimeOnly fg.deobf("curse.maven:iceberg-520110:${iceberg_cf_file_id}")
    runtimeOnly fg.deobf("curse.maven:prism-638111:${prism_cf_file_id}")
    runtimeOnly fg.deobf("curse.maven:chipped-456956:5077656")
    runtimeOnly fg.deobf("curse.maven:resourcefullib-570073:5070629")
    runtimeOnly fg.deobf("curse.maven:athena-841890:4764357")
    runtimeOnly fg.deobf("com.simibubi.create:create-${create_mc_version}:${create_version}:all") {
        transitive = false
    }
/*
    runtimeOnly fg.deobf("net.createmod.ponder:Ponder-Forge-${create_mc_version}:${ponder_version}") {
        transitive = false
    }
    runtimeOnly fg.deobf("dev.engine-room.flywheel:flywheel-forge-${create_mc_version}:${flywheel_version}"){
        transitive = false
    }
*/
    //runtimeOnly fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")

    runtimeOnly fg.deobf("curse.maven:cyclopscore-232758:4905983")
    runtimeOnly fg.deobf("curse.maven:integratedterminals-295910:4925609")
    runtimeOnly fg.deobf("curse.maven:integratedynamics-236307:4925678")
    runtimeOnly fg.deobf("curse.maven:commoncapabilities-247007:4620480")
    runtimeOnly fg.deobf("curse.maven:integratedtunnels-251389:4782861")
    runtimeOnly fg.deobf("curse.maven:mekanism-268560:5125665")
    runtimeOnly fg.deobf("curse.maven:refinedstorage-243076:4844585")
    runtimeOnly fg.deobf("curse.maven:spark-361579:4738952")
    runtimeOnly fg.deobf("curse.maven:geckolib-388172:5188427")
    runtimeOnly fg.deobf("curse.maven:glodium-957920:5226922")
    runtimeOnly fg.deobf("curse.maven:projecte-226410:4901949")
    runtimeOnly fg.deobf("curse.maven:mousetweaks-60089:5338457")
    runtimeOnly fg.deobf("curse.maven:buildinggadgets-298187:5144161")
    //runtimeOnly fg.deobf("curse.maven:railcraft-901491:5898149")
    runtimeOnly fg.deobf("curse.maven:laserio-626839:5074767")
    runtimeOnly fg.deobf("curse.maven:ironfurnaces-237664:5159498")
    runtimeOnly fg.deobf("curse.maven:trashslot-235577:${trashslot_cf_file_id}")

/*
    runtimeOnly fg.deobf("curse.maven:refinedstorage-243076:4465872")
    runtimeOnly fg.deobf("curse.maven:placebo-283644:4629583")
    runtimeOnly fg.deobf("curse.maven:fastworkbench-288885:4579504")
    runtimeOnly fg.deobf("dev.emi:emi-forge:1.0.19+1.19.2")
*/
}

// Example for how to get properties into the manifest for reading by the runtime..
jar {
    manifest {
        attributes([
            "Specification-Title": "examplemod",
            "Specification-Vendor": "examplemodsareus",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"examplemodsareus",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

// Example configuration to allow publishing using the maven-publish task
// we define a custom artifact that is sourced from the reobfJar output task
// and then declare that to be published
// Note you'll need to add a repository here
def reobfFile = file("$buildDir/reobfJar/output.jar")
def reobfArtifact = artifacts.add('default', reobfFile) {
    type 'jar'
    builtBy 'reobfJar'
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact reobfArtifact
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
