# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.debug=false

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.53-beta
neo_version_range=[26.2.0.43-beta,26.3.0)
loader_version_range=[4,)

#runtime deps
jei_mc_version=26.2-neoforge
jei_version=30.7.0.41
create_mc_version=1.21.1
create_version=6.0.4-50
ponder_version=1.0.40
flywheel_version=1.0.1-11
registrate_version=MC1.21-1.3.0+62
ftb_chunks_version=2101.1.1
journeymap_version=1.21.1-6.0.0-beta.32+neoforge
item_borders_cf_file_id=6168720
iceberg_cf_file_id=6186848
prism_cf_file_id=6168652
chipped_cf_file_id=5506938
resourcefullib_cf_file_id=7806326
athena_cf_file_id=5431579
curios_version=15.0.0-beta.2+26.1.2
balm_version=26.2.0.1
craftingtweaks_version=26.2.0.1
ironsspellsnspellbooks_cf_file_id=5618912
geckolib_cf_file_id=5605715
mekanismgenerators_cf_file_id=5574954
carryon_cf_file_id=5649344
sawmill_cf_file_id=6119477
moonlightlib_cf_file_id=6224057
trashslot_version=26.2.0.1
emi_version=1.1.22+1.21.1
rei_version=26.2.820
cloth_config_version=26.2.155
architectury_version=21.0.2
rs_version=3.2.1
jade_cf_file_id=8265965
constructionsticks_version=4.0.0
accessories_cf_file_id=7318047
owolib_cf_file_id=7248199
iris_version=1.10.9+26.1-neoforge
sodium_version=mc26.2-0.9.0-neoforge
